export const TimeZones = [
	{
		value: 'Dateline Standard Time',
		abbr: 'DST',
		offset: -12,
		isdst: false,
		text: '(UTC-12:00) International Date Line West',
		displayTimezone: 'UTC-12:00',
		utc: ['Etc/GMT+12'],
	},
	{
		value: 'UTC-11',
		abbr: 'U',
		offset: -11,
		isdst: false,
		text: '(UTC-11:00) Coordinated Universal Time-11',
		displayTimezone: 'UTC-11:00',
		utc: [
			'Etc/GMT+11',
			'Pacific/Midway',
			'Pacific/Niue',
			'Pacific/Pago_Pago',
		],
	},
	{
		value: 'Hawaiian Standard Time',
		abbr: 'HST',
		offset: -10,
		isdst: false,
		text: '(UTC-10:00) Hawaii',
		displayTimezone: 'UTC-10:00',
		utc: [
			'Etc/GMT+10',
			'Pacific/Honolulu',
			'Pacific/Johnston',
			'Pacific/Rarotonga',
			'Pacific/Tahiti',
		],
	},
	{
		value: 'Alaskan Standard Time',
		abbr: 'AKDT',
		offset: -9,
		isdst: false,
		text: '(UTC-09:00) Alaska',
		displayTimezone: 'UTC-09:00',
		utc: ['America/Anchorage'],
	},
	{
		value: 'Pacific Standard Time',
		abbr: 'PST',
		offset: -8,
		isdst: false,
		text: '(UTC-08:00) Pacific Time (US & Canada)',
		displayTimezone: 'UTC-08:00',
		utc: [
			'America/Los_Angeles',
			'America/Tijuana',
			'America/Vancouver',
			'PST8PDT',
		],
	},
	{
		value: 'US Mountain Standard Time',
		abbr: 'UMST',
		offset: -7,
		isdst: false,
		text: '(UTC-07:00) Arizona',
		displayTimezone: 'UTC-07:00',
		utc: [
			'Etc/GMT+7',
			'America/Creston',
			'America/Dawson',
			'America/Dawson_Creek',
			'America/Hermosillo',
			'America/Phoenix',
			'America/Whitehorse',
		],
	},
	{
		value: 'Central America Standard Time',
		abbr: 'CAST',
		offset: -6,
		isdst: false,
		text: '(UTC-06:00) Central America',
		displayTimezone: 'UTC-06:00',
		utc: [
			'Etc/GMT+6',
			'America/Belize',
			'America/Costa_Rica',
			'America/El_Salvador',
			'America/Guatemala',
			'America/Managua',
			'America/Tegucigalpa',
			'Pacific/Galapagos',
		],
	},
	{
		value: 'Eastern Standard Time',
		abbr: 'EST',
		offset: -5,
		isdst: false,
		text: '(UTC-05:00) Eastern Time (US & Canada)',
		displayTimezone: 'UTC-05:00',
		utc: [
			'Etc/GMT+5',
			'America/Detroit',
			'America/Havana',
			'America/Indiana/Petersburg',
			'America/Indiana/Vincennes',
			'America/Indiana/Winamac',
			'America/Iqaluit',
			'America/Kentucky/Monticello',
			'America/Louisville',
			'America/Montreal',
			'America/Nassau',
			'America/New_York',
			'America/Nipigon',
			'America/Pangnirtung',
			'America/Port-au-Prince',
			'America/Thunder_Bay',
			'America/Toronto',
		],
	},
	{
		value: 'SA Western Standard Time',
		abbr: 'SWST',
		offset: -4,
		isdst: false,
		text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
		displayTimezone: 'UTC-04:00',
		utc: [
			'Etc/GMT+4',
			'America/Anguilla',
			'America/Antigua',
			'America/Aruba',
			'America/Barbados',
			'America/Blanc-Sablon',
			'America/Boa_Vista',
			'America/Curacao',
			'America/Dominica',
			'America/Grand_Turk',
			'America/Grenada',
			'America/Guadeloupe',
			'America/Guyana',
			'America/Kralendijk',
			'America/La_Paz',
			'America/Lower_Princes',
			'America/Manaus',
			'America/Marigot',
			'America/Martinique',
			'America/Montserrat',
			'America/Port_of_Spain',
			'America/Porto_Velho',
			'America/Puerto_Rico',
			'America/Santo_Domingo',
			'America/St_Barthelemy',
			'America/St_Kitts',
			'America/St_Lucia',
			'America/St_Thomas',
			'America/St_Vincent',
			'America/Tortola',
		],
	},
	{
		value: 'E. South America Standard Time',
		abbr: 'ESAST',
		offset: -3,
		isdst: false,
		text: '(UTC-03:00) Brasilia',
		displayTimezone: 'UTC-03:00',
		utc: ['Etc/GMT+3', 'America/Sao_Paulo'],
	},
	{
		value: 'UTC-02',
		abbr: 'U',
		offset: -2,
		isdst: false,
		text: '(UTC-02:00) Coordinated Universal Time-02',
		displayTimezone: 'UTC-02:00',
		utc: ['Etc/GMT+2', 'America/Noronha', 'Atlantic/South_Georgia'],
	},
	{
		value: 'Cape Verde Standard Time',
		abbr: 'CVST',
		offset: -1,
		isdst: false,
		text: '(UTC-01:00) Cape Verde Is.',
		displayTimezone: 'UTC-01:00',
		utc: ['Etc/GMT+1', 'Atlantic/Cape_Verde'],
	},
	{
		value: 'UTC',
		abbr: 'UTC',
		offset: 0,
		isdst: false,
		text: '(UTC) Coordinated Universal Time',
		displayTimezone: 'UTC',
		utc: ['Etc/GMT', 'America/Danmarkshavn'],
	},
	{
		value: 'W. Central Africa Standard Time',
		abbr: 'WCAST',
		offset: 1,
		isdst: false,
		text: '(UTC+01:00) West Central Africa',
		displayTimezone: 'UTC+01:00',
		utc: [
			'Etc/GMT-1',
			'Africa/Algiers',
			'Africa/Bangui',
			'Africa/Brazzaville',
			'Africa/Douala',
			'Africa/Kinshasa',
			'Africa/Lagos',
			'Africa/Libreville',
			'Africa/Luanda',
			'Africa/Malabo',
			'Africa/Ndjamena',
			'Africa/Niamey',
			'Africa/Porto-Novo',
			'Africa/Tunis',
		],
	},
	{
		value: 'South Africa Standard Time',
		abbr: 'SAST',
		offset: 2,
		isdst: false,
		text: '(UTC+02:00) Harare, Pretoria',
		displayTimezone: 'UTC+02:00',
		utc: [
			'Etc/GMT-2',
			'Africa/Blantyre',
			'Africa/Bujumbura',
			'Africa/Gaborone',
			'Africa/Harare',
			'Africa/Johannesburg',
			'Africa/Kigali',
			'Africa/Lubumbashi',
			'Africa/Lusaka',
			'Africa/Maputo',
			'Africa/Maseru',
			'Africa/Mbabane',
		],
	},
	{
		value: 'E. Africa Standard Time',
		abbr: 'EAST',
		offset: 3,
		isdst: false,
		text: '(UTC+03:00) Nairobi',
		displayTimezone: 'UTC+03:00',
		utc: [
			'Etc/GMT-3',
			'Africa/Addis_Ababa',
			'Africa/Asmera',
			'Africa/Dar_es_Salaam',
			'Africa/Djibouti',
			'Africa/Juba',
			'Africa/Kampala',
			'Africa/Khartoum',
			'Africa/Mogadishu',
			'Africa/Nairobi',
			'Antarctica/Syowa',
			'Indian/Antananarivo',
			'Indian/Comoro',
			'Indian/Mayotte',
		],
	},
	{
		value: 'Arabian Standard Time',
		abbr: 'AST',
		offset: 4,
		isdst: false,
		text: '(UTC+04:00) Abu Dhabi, Muscat',
		displayTimezone: 'UTC+04:00',
		utc: ['Etc/GMT-4', 'Asia/Dubai', 'Asia/Muscat'],
	},
	{
		value: 'Afghanistan Standard Time',
		abbr: 'AST',
		offset: 4.5,
		isdst: false,
		text: '(UTC+04:30) Kabul',
		displayTimezone: 'UTC+04:30',
		utc: ['Asia/Kabul'],
	},
	{
		value: 'West Asia Standard Time',
		abbr: 'WAST',
		offset: 5,
		isdst: false,
		text: '(UTC+05:00) Ashgabat, Tashkent',
		displayTimezone: 'UTC+05:00',
		utc: [
			'Etc/GMT-5',
			'Antarctica/Mawson',
			'Asia/Aqtau',
			'Asia/Aqtobe',
			'Asia/Ashgabat',
			'Asia/Dushanbe',
			'Asia/Oral',
			'Asia/Samarkand',
			'Asia/Tashkent',
			'Indian/Kerguelen',
			'Indian/Maldives',
		],
	},
	{
		value: 'India Standard Time',
		abbr: 'IST',
		offset: 5.5,
		isdst: false,
		text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
		displayTimezone: 'UTC+05:30',
		utc: ['Asia/Kolkata', 'Asia/Calcutta'],
	},
	{
		value: 'Nepal Standard Time',
		abbr: 'NST',
		offset: 5.75,
		isdst: false,
		text: '(UTC+05:45) Kathmandu',
		displayTimezone: 'UTC+05:45',
		utc: ['Asia/Kathmandu'],
	},
	{
		value: 'Bangladesh Standard Time',
		abbr: 'BST',
		offset: 6,
		isdst: false,
		text: '(UTC+06:00) Dhaka',
		displayTimezone: 'UTC+06:00',
		utc: ['Etc/GMT-6', 'Asia/Dhaka', 'Asia/Thimphu'],
	},
	{
		value: 'Myanmar Standard Time',
		abbr: 'MST',
		offset: 6.5,
		isdst: false,
		text: '(UTC+06:30) Yangon (Rangoon)',
		displayTimezone: 'UTC+06:30',
		utc: ['Asia/Rangoon', 'Indian/Cocos'],
	},
	{
		value: 'SE Asia Standard Time',
		abbr: 'SAST',
		offset: 7,
		isdst: false,
		text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
		displayTimezone: 'UTC+07:00',
		utc: [
			'Etc/GMT-7',
			'Asia/Bangkok',
			'Antarctica/Davis',
			'Asia/Hovd',
			'Asia/Jakarta',
			'Asia/Phnom_Penh',
			'Asia/Pontianak',
			'Asia/Saigon',
			'Asia/Vientiane',
			'Indian/Christmas',
		],
	},
	{
		value: 'Singapore Standard Time',
		abbr: 'MPST',
		offset: 8,
		isdst: false,
		text: '(UTC+08:00) Kuala Lumpur, Singapore',
		displayTimezone: 'UTC+08:00',
		utc: [
			'Etc/GMT-8',
			'Asia/Brunei',
			'Asia/Kuala_Lumpur',
			'Asia/Kuching',
			'Asia/Makassar',
			'Asia/Manila',
			'Asia/Singapore',
		],
	},
	{
		value: 'Japan Standard Time',
		abbr: 'JST',
		offset: 9,
		isdst: false,
		text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
		displayTimezone: 'UTC+09:00',
		utc: [
			'Etc/GMT-9',
			'Asia/Tokyo',
			'Asia/Dili',
			'Asia/Jayapura',
			'Pacific/Palau',
		],
	},
	{
		value: 'AUS Central Standard Time',
		abbr: 'ACST',
		offset: 9.5,
		isdst: false,
		text: '(UTC+09:30) Darwin',
		displayTimezone: 'UTC+09:30',
		utc: ['Australia/Darwin'],
	},
	{
		value: 'West Pacific Standard Time',
		abbr: 'WPST',
		offset: 10,
		isdst: false,
		text: '(UTC+10:00) Guam, Port Moresby',
		displayTimezone: 'UTC+10:00',
		utc: [
			'Etc/GMT-10',
			'Pacific/Port_Moresby',
			'Antarctica/DumontDUrville',
			'Pacific/Guam',
			'Pacific/Saipan',
			'Pacific/Truk',
		],
	},
	{
		value: 'Central Pacific Standard Time',
		abbr: 'CPST',
		offset: 11,
		isdst: false,
		text: '(UTC+11:00) Solomon Is., New Caledonia',
		displayTimezone: 'UTC+11:00',
		utc: [
			'Etc/GMT-11',
			'Antarctica/Macquarie',
			'Pacific/Efate',
			'Pacific/Guadalcanal',
			'Pacific/Kosrae',
			'Pacific/Noumea',
			'Pacific/Ponape',
		],
	},
	{
		value: 'UTC+12',
		abbr: 'U',
		offset: 12,
		isdst: false,
		text: '(UTC+12:00) Coordinated Universal Time+12',
		displayTimezone: 'UTC+12:00',
		utc: [
			'Etc/GMT-12',
			'Pacific/Funafuti',
			'Pacific/Kwajalein',
			'Pacific/Majuro',
			'Pacific/Nauru',
			'Pacific/Tarawa',
			'Pacific/Wake',
			'Pacific/Wallis',
		],
	},
	{
		value: 'Tonga Standard Time',
		abbr: 'TST',
		offset: 13,
		isdst: false,
		text: "(UTC+13:00) Nuku'alofa",
		displayTimezone: 'UTC+13:00',
		utc: [
			'Etc/GMT-13',
			'Pacific/Enderbury',
			'Pacific/Fakaofo',
			'Pacific/Tongatapu',
		],
	},
];
